version: "3.8"

services:
  api:
    build: .
    restart: always
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=hackathon_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackathon_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
